
services:
  jobs-api:
    image: papopapota/jobs-api:v1.1.29
    restart: unless-stopped
    environment:
      NODE_ENV: production
      MONGO_URI: ${MONGO_URI}
      JWT_SECRET: ${JWT_SECRET}
      JWT_LIFETIME: ${JWT_LIFETIME}
      PORT: ${PORT}
      TRADERMADE_API_KEY: ${TRADERMADE_API_KEY}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

